language: node_js
os:
- linux
- windows
- osx

node_js:
 - 12
 - 10
 
install:
  - npm install -g
  - npm install --only-dev

script:
  - node src/main.js
  - node src/testing.js
  - isbin 00001010101001001011010110101
